#!/usr/bin/env bash
# configures nginx to display string
sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo service nginx start
echo "Holberton School" > /var/www/html/index.html
