#!/usr/bin/env bash
# configures ubuntu with nginx and custom header

server_name="$(uname -n)"

sudo apt-get update
sudo apt-get -y install nginx
sed -i "19 i \tadd_header X-Served-By $server_name" /etc/nginx/sites-available/default
sudo nginx -s reload
sudo nginx -s restart
