#!/usr/bin/env bash
# creates holbertonscript.pid
# prints To infinity and beyond
# prints I hate the kill command when receiving SIGTERM
# prints Y U no love me?! when receiving SIGINT
# deletes holbertonscript.pid and terminates when receiving SIGQUIT or SIGTERM
echo $$ > /var/run/holbertonscript.pid

trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done

