#!/usr/bin/env bash
# print To infinity and beond!
# print I am invincible!!! when receiving SIGTERM

trap "echo I am invincible!!!" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done

