#!/usr/bin/env bash
#prints 1-20
#4th loop prints "bad luck from China"
#9th loop prints "bad luck from Japan"
#17th loop prints "bad luck from Italy"
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac

	((i++))
done

