#!/usr/bin/env bash
# make localhost resolve to 127.0.0.2
# make facebook.com resolve to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i "
/localhost/ c\
127.0.0.2 localhost\n8.8.8.8 facebook.com
" ~/hosts.new
cp -f ~/hosts.new /etc/hosts

